---
- hosts: production
  become: true
  vars:
    app_name: sandco_landing
    image_name: sandco_landing_image
    port_number: 3400
    ufw_nginx_alias: Nginx HTTP
    hugo_source_dir: "/home/jls83/{{ app_name }}"
    hugo_destination_dir: "{{ hugo_source_dir }}/public"
    git_repo_url: "https://github.com/jls83/{{ app_name }}.git"
    nginx_config_source: "templates/{{ app_name }}.conf"
    nginx_config_dest: "/etc/nginx/sites-available/{{ app_name }}.conf"
  environment:
      PYTHONPATH: "{{ lookup('env','PYTHONPATH') }}:/usr/local/lib/python2.7/dist-packages:/usr/local/lib/python2.7/site-packages"
  tasks:
    # Server set up/software install
    - name: Update apt
      apt: update_cache=yes

    - name: Install Pip
      apt:
        state: latest
        name: python-pip

    - name: Install Nginx
      apt:
        name: nginx

    - name: Install hugo
      command: snap install hugo
      become: false

    - name: Install `docker` and `requests` pip packages
      pip:
        name:
          - docker
          - requests>=2.20.1

    # Nginx steps (part 2)
    - name: Allow Nginx for UFW
      ufw:
        rule: allow
        name: "Nginx HTTP"

    - name: Copy Nginx config file
      template:
        src: "{{ nginx_config_source }}"
        dest: "{{ nginx_config_dest }}"

    - name: Create Nginx symlink
      file:
        src: "{{ nginx_config_dest }}"
        dest: /etc/nginx/sites-enabled/{{ app_name }}.conf
        state: link

    # Pull down repo and build
    - name: Pull down repo from Github
      git:
        repo: "{{  git_repo_url  }}"
        dest: "{{ hugo_source_dir }}"

    - name: Create destination directory
      file:
        path: "{{ hugo_destination_dir }}"
        state: directory
      become: false

    - name: Build hugo site
      command: snap run hugo -s {{ hugo_source_dir }} -d {{ hugo_destination_dir }} --minify
      become: false

    # Docker steps
    - name: Remove old Docker image
      docker_image:
        name: "{{ image_name }}"
        state: absent
        force: yes

    - name: Build new Docker image
      docker_image:
        path: "{{ hugo_source_dir }}"
        name: "{{ image_name }}"
        push: no

    - name: Stop all `sandco_landing` containers
      docker_container:
        name: "{{ app_name }}"
        image: "{{ image_name }}"
        state: stopped

    - name: Run Docker container
      docker_container:
        name: "{{ app_name }}"
        image: "{{ image_name }}"
        state: started
        ports: "{{ port_number }}:80"
      notify: restart nginx
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

